#include "hal/ledmatrix/ledmatrix.h"

const LedMatrix_Config_t LedMatrix_Config[LED_MATRIX_MAX] =
{
    [LED_MATRIX_1] = {
        .row_port = {MATRIX_PORTB,MATRIX_PORTB,MATRIX_PORTB,MATRIX_PORTC,MATRIX_PORTC,MATRIX_PORTB,MATRIX_PORTB,MATRIX_PORTB},
        .row_pins = {MATRIX_PIN0, MATRIX_PIN1, MATRIX_PIN2, MATRIX_PIN13, MATRIX_PIN14, MATRIX_PIN5, MATRIX_PIN6, MATRIX_PIN7},

        .col_port = {MATRIX_PORTB,MATRIX_PORTB,MATRIX_PORTB,MATRIX_PORTB,MATRIX_PORTB,MATRIX_PORTB,MATRIX_PORTB,MATRIX_PORTC},
        .col_pins = {MATRIX_PIN8, MATRIX_PIN9, MATRIX_PIN10, MATRIX_PIN12, MATRIX_PIN13, MATRIX_PIN14, MATRIX_PIN15, MATRIX_PIN15},
        .anode = ROW
    }
};


